---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: spc1
      labels:
        app: web
    spec:
      containers:
        - name: spc
          image: httpd 
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /admin
              port: 8080
          ports: 
            containerPort: 8080
            protocol: TCP         
