---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment1
  labels:
spec:
  minReadySeconds: "10"
  replicas: "4"
  selector:
    matchLabels:
      app: httpdserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: httpd
      labels:
        app: httpdserver
    spec:
      containers:
        - name: apache
          image: httpd 
          livenessProbe:
            httpGet:
              path: /
              port: "80"
          readinessProbe:
            httpGet:
              path: /admin
              port: "80"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi   
          ports:
            containerPort: "80"
            protocol: TCP         
