---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec: 
  containers:
    - name: httpd
      image: httpd:2.4
      args: 
        - sleep
          1d
      ports:
        - containerPort: 80
          protocol: "TCP"
            
    
    


