---
apiVersion: v1
kind: Pod
metadata:
  name: trail3
spec:
  containers:
    - name: psql
      image: postgres:alpine3.18
      env:
        - name: POSTGRES_PASSWORD
          value: admin123
        - name: POSTGRES_USER
          value: nop
        - name: POSTGRES_DB
          value: emp 
