---
apiVersion: v1 
kind: Pod
metadata:
  name: trail6
spec:
  initContainers:
    - name: initcontainer1 
      image: alpine:3.17
      args:
        - sleep
        - 30s
  containers:
    - name: httpdcontainer
      image: httpd:2.4
      resources:
        limits: 
          cpu: 1000m
          memory: 0.5Gi



