---
apiVersion: v1
kind: Pod
metadata: 
  name: nop
spec:
  containers:
    - name: nop
      image: nopcommerceteam/nopcommerce:4.60.6
      ports:
        - containerPort: "5000"
      resources:
        requests: 
          cpu: 500m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 4Gi