---
apiVersion: v1
kind: Pod
metadata: 
  name: db 
spec:
  containers:
     - name: sql
       image: mysql:8.0-debian
       env:
         - name: MYSQL_ROOT_PASSWORD
           value: admin123     
         - name: MYSQL_DATABASE
           value: emp
         - name: MYSQL_USER
           value: nop
         - name: MYSQL_PASSWORD
           value: admin123
