---
apiVersion: apps/v1
Kind: Deployment
metadata: 
  name: dp1
spec: 
  minReadySeconds: 10
  replicas: 4
  selector: 
    matchLabels:
      app: spc
  strategy: 
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: spc
      labels:
        app: spec
        version: "1.0"
    spec:
      containers:
        - name: spc1.0
          image: shaikkhajaibrahim/spcjan2024:1.0
          ports:
           - containerPort: "8080"
             name: spring
          resources:
            limits:
              cpu: 1000m
              memory: 500Gi

          


