---
apiVersion: v1
kind: Pod
metadata: 
  name: nop
spec:
  containers:
     - name: apache
       image: httpd:2.4.59
       resources:
         requests:
           cpu: 500m
           memory: 256Mi
         limits:
           cpu: 1000m
           memory: 1Gi